config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  root 'links#index'
  resources :links do
    member do
      put 'upvote', to: 'links#upvote'
      put 'downvote', to: 'links#downvote'
    end
    resources :comments
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
  #comments will be rendered in descending order by default.
  default_scope { order(created_at: :desc) }
  #use the below scope if descending order shouldn't be the default order.
  #scope :descending, -> {order(created_at: :desc)}
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable
  def self.search(term)
    if term
      where('title LIKE ?', "#{term}").order('id DESC')
    else
      order('id DESC')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :links, dependent: :destroy
  has_many :comments, dependent: :destroy
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_paramaters, if: :devise_controller?

  protected

  def configure_permitted_paramaters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @link = Link.find(params[:link_id])
    @user = current_user
    @comment = Comment.new(comment_params)
    @comment.user_id = @user.id
    @comment.link_id = @link.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /links
  # GET /links.json
  def index
    @links = Link.search(params[:term])
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @comments = @link.comments
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #made possible by acts_as_votable gem
  def upvote
    @link = Link.find(params[:id])
    @user = current_user
    @user.likes @link
    redirect_back fallback_location: root_path
  end

  def downvote
    @link = Link.find(params[:id])
    @user = current_user
    @user.dislikes @link
    redirect_back fallback_location: root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link_id %>
    <%= form.number_field :link_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greenit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <%= link_to 'Green-it </>', root_path, class: 'brand-logo' %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to 'Hottest Links', root_path %>
            <% if user_signed_in? %>
              <li><%= link_to 'Create a Post', new_link_path %></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
              <li><%= link_to 'Account', edit_user_registration_path %></li>
            <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
          </ul>
          <%= form_tag(links_path, method: :get, class: 'search-form hide-on-med-and-down', autocomplete: 'off') do %>
            <div class="input-field" id="search-field-wrapper">
              <%= text_field_tag :term, params[:term], required: true, class: 'search-field', type: 'search' %>
              <label class="label-icon" for="term"><i class="material-icons">search</i></label>
              <i class="material-icons">close</i>
            </div>
          <% end %>
          <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>
      </nav>

    </div>
    <ul id="slide-out" class="sidenav">
      <li><%= link_to 'Hottest Links', root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Create a Post', new_link_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
        <li><%= link_to 'Account', edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    </ul>


    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %> </p>
    <div class="parent-div">
      <%= yield %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/links/_comment_form.html.erb
<div class="new-comment">
  <%= form_for [@link, Comment.new] do |f| %>
    <%= f.text_field :body, required: true, autocomplete: 'off' %>
    <%= f.submit "Post Comment", class: 'btn' %>
  <% end %>
</div>

app/views/links/_comments.html.erb
<div class="comments">
  <ul class="collection">
    <% @comments.each do |comment| %>

      <li class="collection-item"><p class="comment-age-tag">Posted by <%= comment.user.name%> about <%= time_ago_in_words(comment.created_at)%> ago</p> <br>
        <p class="comment-body"><%= comment.body %></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn' %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Links</h1>

<% @links.each do |link| %>
  <ul class="collection">
    <li class="collection-item">
      <%= link_to link do %>
        <h2 class="title"><%= link.title %></h2>
      <% end %>
      <p>Created by <%= link.user.name %> about <%= time_ago_in_words(link.created_at) %> ago<br>
         <% if link.user == current_user %>
           <td><%= link_to 'Edit', edit_link_path(link) %></td>
           <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% end %>
      </p>

      <%=link_to downvote_link_path(link), method: :put, class: 'secondary-content' do %>
        <i class="material-icons">arrow_downward</i><span>
      <% end %>

      <div class="secondary-content"><%= link.get_likes.size - link.get_dislikes.size %></div>

      <%=link_to upvote_link_path(link), method: :put, class: 'secondary-content' do %>
        <i class="material-icons">arrow_upward</i><span>
      <% end %>

    </li>
  </ul>
<% end %>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<h1>
  <%= @link.title %>
</h1>

<div class="show-link-d">
  <strong>Url:</strong>
  <%= link_to @link.url, @link.url %>
  <br>
  <div class="show-votes">
    <%=link_to downvote_link_path(@link), method: :put, class: 'vote-icon' do %>
      <i class="material-icons">arrow_downward</i><span>
    <% end %>

    <span><%= @link.get_likes.size - @link.get_dislikes.size %></span>

    <%=link_to upvote_link_path(@link), method: :put, class: 'vote-icon' do %>
      <i class="material-icons">arrow_upward</i><span>
    <% end %>
  </div>
</div>
<%= render 'comment_form' %>
<%= render 'comments' %>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>